version: 2.1
orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  build_and_test:
    docker:
      - image: circleci/ruby:3.1.0-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run: gem install bundler
      - ruby/bundle-install
      - run: bundle exec rspec

workflows:
  build_and_test_workflow:
    jobs:
       - build_and_test
