version: 2.1
orbs:
  ruby: circleci/ruby@1.4.0
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    docker:
      - image: cimg/ruby:3.1-node
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rspec
      - ruby/install-deps
      - ruby/rspec-test

workflows:
  build_and_test_deploy:
    jobs:
      - build_and_test
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
